api/v1/harborcluster_types.go
fix https://github.com/goharbor/harbor-cluster-operator/issues/55
Signed-off-by: xiaoyang zhu <zhuxiaoyang1996@gmail.com>
=> fix field  in JobService

api/v1/harborcluster_types.go
=> Remove defaulting for ImageSource. Fix typo.

PROJECT, api/v1/groupversion_info.go, config/crd/kustomization.yaml, config/rbac/harborcluster_editor_role.yaml, config/rbac/harborcluster_viewer_role.yaml, config/samples/goharbor_v1_harborcluster.yaml, controllers/harborcluster_controller.go
Fixes [#53 ](https://github.com/goharbor/harbor-cluster-operator/issues/53)
=> update group to `cluster.goharbor.io`.

api/v1/harborcluster_types.go, docs/cr_HarborCluster_spec.md
=> fix resource definition

config/crd/patches/cainjection_in_harborclusters.yaml, config/crd/patches/webhook_in_harborclusters.yaml
=> fix crd api group

controllers/harbor/provision.go, controllers/k8s/labels.go
=> fix cycle import.

api/v1/harborcluster_types.go, controllers/storage/constants.go, controllers/storage/delete.go, controllers/storage/minio.go, controllers/storage/provision.go, controllers/storage/scale.go, controllers/storage/update.go
Signed-off-by: xiaoyang zhu <zhuxiaoyang1996@gmail.com>
=> minio scale implement

controllers/cache/client.go, controllers/cache/constants.go, controllers/cache/readiness.go, controllers/cache/utils.go
Support external redis which need password
Fixes #90
=> fix(cache) support external redis which need password

config/samples/external-sentinel.yaml, config/samples/external-server.yaml, controllers/cache/readiness.go, controllers/cache/redis.go, controllers/cache/utils.go, controllers/database/postgresql.go
fix get external secret panic
Fixes #96
=> fix(cache): fix get external secret panic

controllers/storage/client.go, controllers/storage/minio.go, go.mod, go.sum
=> minio init implemate

controllers/harbor/errors.go, controllers/harbor/harbor.go, controllers/harbor/provision.go, controllers/harbor/scale.go, controllers/harbor/update.go
=> fix(harbor): implements harbor cr update handler.

controllers/storage/update.go
Signed-off-by: xiaoyang zhu <zhuxiaoyang1996@gmail.com>
=> fix external storage update return data

controllers/storage/minio.go, controllers/storage/provision.go
Signed-off-by: xiaoyang zhu <zhuxiaoyang1996@gmail.com>
=> fix minio svc and secret lifecycle

controllers/storage/provision.go
=> fix error when minio secret already exists

controllers/database/api/postgresql_type.go, controllers/database/generate.go, controllers/harborcluster_controller.go
Database need to add pg_hba whitelisot
Fixes #114
=> fix(database):database need to add pg_hba whitelist

controllers/harbor/provision.go, controllers/storage/provision.go, lcm/property.go
=> fix(storage): provide in-cluster storage secret property.

api/v1/harborcluster_webhook.go, controllers/harbor/cert.go, controllers/harbor/errors.go, controllers/harbor/provision.go, controllers/harborcluster_controller.go, main.go
Add check function to make sure Issuer will be created.
Fixes #124
=> fix(harbor):fix miss Issuer for registry cert

controllers/storage/provision.go
Fix inCluster minio regionendpoint
=> fix(storage): fix inCluster minio regionendpoint

controllers/storage/minio.go
=> fix minio status return

docs/installation.md
=> feat(doc):  add installation.md

.github/workflows/ci.yml, Makefile
call `make test docker-build`
push docker image to hub.docker/golang/harbor-cluster-operator:dev
=> feat(CI) add CI for test and docker build

controllers/harborcluster_controller.go
Add reconcile wait requeue time
Fixes #147
=> fix(reconcile) add reconcile wait requeue time

controllers/database/generate.go, controllers/database/readiness.go, controllers/harbor/provision.go
Fix the problem that Notary is unavailable, and the optional component uses the database separately.
Fixes #143
=> fix(notary) fix the problem that Notary is unavailable

Dockerfile, Makefile, config/manager/manager.yaml, controllers/cache/client.go, controllers/cache/constants.go, controllers/cache/generate.go, controllers/cache/provision.go, controllers/cache/readiness.go, controllers/cache/utils.go, controllers/database/generate.go
Support provison inCluster single redis
Fixes #136
=> feat(cache) support provison inCluster single redis

api/v1/harborcluster_types.go
=> feat(api): print more info when using `kubectl get harborcluster`

docs/installation_local.md
Signed-off-by: Steven Zou <szou@vmware.com>
=> doc(installation): add guide to deploy harbor on Kind cluster

docs/installation.md
=> fix(doc): add installation.md

api/v1/harborcluster_types.go, controllers/storage/provision.go
add s3 storage auth info.
CLOSE #141
=> fix(chartmuseum): fix optional component `Chartmuseum` is crashed

controllers/database/generate.go, controllers/database/readiness.go, controllers/database/utils.go
=> fix clair crash

controllers/database/readiness.go, controllers/harborcluster_controller.go
Add minio.min.io serviceaccount
=> fix(bug): add minio.min.io serviceaccount

controllers/harbor/provision.go
Fix NPE in the operator controller
Fix #169
=> fix(harbor): fix NPE in the operator controller

manifests/README.md, manifests/all-in-one.yaml, manifests/core-operator/all-core-operator-resources.yaml, manifests/kustomization.yaml, manifests/namespaces/namespaces.yaml, manifests/patches/postgres/cluster-rb-patch.yaml, manifests/patches/postgres/namespace-patch.yaml, manifests/patches/postgres/namespace-replace-patch.yaml, manifests/patches/redis/cluster-rb-patch.yaml, manifests/patches/redis/namespace-patch.yaml
* refer core operator kustomization template (local copy)
* refer cluster operator kustomization template (local)
* refer redis operator deployment manifest (github)
* refer psql operator kustomization template (github)
* refer minio operator kustomization template (github)
* add patch yamls
Signed-off-by: Steven Zou <szou@vmware.com>
=> feat(operator):add kustomization templates

controllers/harbor/provision.go, controllers/storage/constants.go, controllers/storage/minio.go, controllers/storage/provision.go, lcm/property.go
=> fix(storage): split storage secret for chart museum.

README.md, docs/README.md, docs/architecture.md, docs/cr_HarborCluster_spec.md, docs/installation.md, docs/installation_external.md, docs/sample_deploy_guide.md
- update installation md file
- update sample deployment md file
- update README
- update harbor cluster spec md file
Signed-off-by: Steven Zou <szou@vmware.com>
=> doc(installation):re-organize installation guides

docs/installation.md, docs/sample_deploy_guide.md
Signed-off-by: Ziming Zhang <zziming@vmware.com>
=> fix_doc_sample

controllers/cache/generate.go, controllers/cache/labels.go, controllers/cache/utils.go, controllers/database/utils.go, controllers/image/image.go, controllers/storage/minio.go, controllers/storage/provision.go
=> fix(golint): fix golint error

docs/sample_deploy_guide.md, manifests/kustomization.yaml, samples/incluster/README.md, samples/incluster/inCluster.yaml
- change controller image tags to rc1
- add sample folder and incluster sample manifest
- add more links in the installtion guide
Signed-off-by: Steven Zou <szou@vmware.com>
=> doc(installation):add and update installation guides

docs/installation_external.md
=> fix(doc): update doc

controllers/storage/provision.go
fix https://github.com/goharbor/harbor-cluster-operator/issues/220
=> fix ing svc name

controllers/harborcluster_controller.go
fix https://github.com/goharbor/harbor-cluster-operator/issues/218
=> update rbac ingresses

controllers/storage/provision.go
fix https://github.com/goharbor/harbor-cluster-operator/issues/219
=> fix minio secret data

.github/workflows/ci.yml
Change github ci kubebuilder version 2.0.1 to 2.3.1
Fix #226
=> feat(ci): Change github ci kubebuilder version

.github/workflows/ci.yml, apis/goharbor.io/v1alpha1/harborcluster_webhook.go, docs/installation_external.md, docs/installation_local.md, manifests/all-in-one.yaml, samples/incluster/inCluster.yaml
Signed-off-by: Ziming Zhang <zziming@vmware.com>
=> fix harbor version in yamls

.github/workflows/ci.yml
Signed-off-by: Ziming Zhang <zziming@vmware.com>
=> feat(ci) fix docker image in CI
